### ISSUE TITLE
Error "UNC paths are not supported.  Defaulting to Windows directory."

### ISSUE THREAD

**Issue by anodynos** [lalilaloe/wttab#23]
This is is the same error as #17 but in WSL 1, therefore I'\m opening as a new error: 

```
anodynos@Dellino:~$ wttab
'\\wsl$\Ubuntu-22.04\home\anodynos'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
file:///home/anodynos/.asdf/installs/nodejs/16.18.0/lib/node_modules/wttab/index.js:145
    return profile.source.split(".").pop().decapitalize();
                          ^

TypeError: Cannot read properties of undefined (reading 'split')
    at getProfileCommand (file:///home/anodynos/.asdf/installs/nodejs/16.18.0/lib/node_modules/wttab/index.js:145:27)
    at file:///home/anodynos/.asdf/installs/nodejs/16.18.0/lib/node_modules/wttab/index.js:150:58
    at Array.map (<anonymous>)
    at availableProfiles (file:///home/anodynos/.asdf/installs/nodejs/16.18.0/lib/node_modules/wttab/index.js:150:33)
    at file:///home/anodynos/.asdf/installs/nodejs/16.18.0/lib/node_modules/wttab/index.js:178:33
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

Details: 
- Ubuntu-22.04 on WSL 1
- Windows 10 Pro 22H2 OS Build 19045.2673

**Comment by anodynos** [comment]
I've tried the main version that isn't published, and it works, although I'm still getting the error (twice) on the origin terminal: 

```
anodynos@Dellino:~/projects$ wttab --profile wsl --window --title "Foobar" ls
'\\wsl$\Ubuntu-22.04\home\anodynos\projects'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
stderr: '\\wsl$\Ubuntu-22.04\home\anodynos\projects'
CMD.EXE was started with the above path as the current directory.
```

**Comment by anodynos** [comment]
It seems the problem is with cmd.exe it self, and there's no solution arround: https://social.technet.microsoft.com/Forums/ie/en-US/2c44083d-86d0-450d-b24e-955cfc473872/unc-paths-are-not-supported-error-message-comes-up-is-it-ok-to-ignore?forum=ITCG

Running `wt.exe -w -1  --title "Foobar" -p "Ubuntu-20.04" bash -c "cd /home/anodynos/projects && echo ls && ls\; exec bash 2>&1"` works just fine, why do you need to call cmd.exe at all?
