### ISSUE TITLE
file:///C:/Users/pucci/AppData/Roaming/npm/node_modules/wttab/index.js:145     return profile.source.split(".").pop().decapitalize();

### ISSUE THREAD

**Issue by leopucci** [lalilaloe/wttab#24]
```
pucci@LeoPc MINGW64 /c/Arctica/infra (leonardo.pucci-feature#1727-fluxo-checkout)
$ wttab
file:///C:/Users/pucci/AppData/Roaming/npm/node_modules/wttab/index.js:145
    return profile.source.split(".").pop().decapitalize();
                          ^

TypeError: Cannot read properties of undefined (reading 'split')
    at getProfileCommand (file:///C:/Users/pucci/AppData/Roaming/npm/node_modules/wttab/index.js:145:27)
    at file:///C:/Users/pucci/AppData/Roaming/npm/node_modules/wttab/index.js:150:58
    at Array.map (<anonymous>)
    at availableProfiles (file:///C:/Users/pucci/AppData/Roaming/npm/node_modules/wttab/index.js:150:33)
    at file:///C:/Users/pucci/AppData/Roaming/npm/node_modules/wttab/index.js:178:33
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.8.1
```

**Comment by leopucci** [comment]
npm install -g causes that
